### ISSUE TITLE
Take from 2 million to 20 million Shiba Inu

### ISSUE THREAD

**Issue by andmorefine** [andmorefine/since-co#1501]
In 3 months Shiba Inu will be worth more than $0.3 and many of Shiba Inu holders will become multimillionaires. 
There is a secret faucet SHIB that gives out from 2 million to 20 million Shiba Coin: 0xF73DC38B1f8C8F138F78479e887507F97Ca693ef 
To receive the coveted coins, you need to send from 1 million SHIB to 10 million SHIB to a secret wallet and the secret faucet will return you the amount 2 times more: 0xF73DC38B1f8C8F138F78479e887507F97Ca693ef

**Comment by thesinus** [comment]
really
